# Generated by Django 5.1.1 on 2024-10-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('po_number', models.CharField(max_length=100)),
                ('location_from', models.CharField(max_length=255)),
                ('location_to', models.CharField(max_length=255)),
                ('dh_miles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lumper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
