# Generated by Django 5.1.1 on 2024-10-08 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrecord',
            name='dh_miles',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='food',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='fuel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='location_from',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='location_to',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='lumper',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='miles',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='pay',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
